name: 'cook-book'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - '5173:5173'
    volumes:
      - ./:/var/www/app
      - /var/www/app/node_modules
    command: npm run dev -- --host
